= Apache Web Server
Matt Germonprez <germonprez@gmail.com>
v1.2, Sept 1, 2021
ifndef::bound[:imagesdir: figs]
:source-highlighter: rouge
:rouge-style: github
:icons: font
:experimental:

This exercise will help you set up and configure the Apache Web Server.

== Learning Objectives

By the end of this lesson, you will be able to:

* Setup an Apache Web Server
* Connect to Apache via your local browser
* Modify Apache directives to change the server behavior
* Install Apache modules to enhance the server capabilities

= Stop your instances when you are done with the lab. 

This is a reminder to stop your servers when you are done with your labs/assignments. You don't want to use unnecessary credits when you aren't using your instances. 

Simply point your cursor over the instance, right click, and say STOP INSTANCE --> OR check the box next to the instance and then at the top, change instance state to STOP INSTANCE. 

Again, make sure you stop the instances so as to not use up your credits. 


== Steps

=== Step 1: SSH into one of your AWS instances, Install Apache, and Test the Site

Apache is a very popular web server. You can check out the Market Share Survey here to get some idea of how it stacks up against other web servers (market-wise):

https://news.netcraft.com/archives/2018/08/24/august-2018-web-server-survey.html

Quite simply to install the Apache on your AWS machine:
 
 $ sudo yum update
 $ sudo yum install httpd

Answer the one question on space requirements during the installation and the web server will be downloaded and installed via YUM.

Once the installation is complete, you need to start the server:

 $ sudo service httpd start

That's it. The command should look like it did nothing -- just returning you to the next command prompt line. All is good.

Now, you will have to go into your Instance on AWS and modify the security rules to include HTTP running on port 80, open to everyone. 

Now open up your browser on your local (host) computer and type the following in the address:

http://YOUR.PUBLIC.IP.ADDRESS

You should see the Apache It Worked! page.

=== Step 2: Modify Apache: Directories, Files, and Directives

Up to this point, you have installed the default Apache Web Server. This includes a variety of functions but not all of them. In short, Apache doesn't ship with all functionality running -- you have to turn things on (or off as you'd like).

Before you do that, you have to get some bearings on the layout of the Apache file structure.

First, change the default html page. To do so, you'll have to navigate to the html directory on Ubuntu:

 $ cd /var/www
 $ ls

You'll see the html folder there

 $ cd html
 $ ls

Now create a new index.html file with your favorite editor (emacs, vim, nano):

 $ sudo nano index.html

(Yes, nano is awesome). Type anything you want in that file. It could be text, it could be HTML, it doesn't really matter. When you are done save and close (if you are using nano -- kbd:[Ctrl+O] and enter to save, kbd:[Ctrl+X] to exit). Now reload your http://YOUR.PUBLIC.IP.ADDRESS page on your browser -- you should see your changes.

Now that you know where the HTML pages are located, track down the configuration files. They are located in

 $ cd /etc/httpd/conf
 $ ls

There are several important files in here but start with httpd.conf.

 $ sudo nano httpd.conf

You'll see in the file that there are a lot of comments and a few uncommented lines. These uncommented lines are the directives - they allow me to tweak existing functionality on Apache. Perhaps the most interesting part of the httpd.conf file are the following lines:

.httpd.conf snippet
[source,apache]
----
ServerRoot "/etc/httpd"

#
# Listen: Allows you to bind Apache to specific IP addresses and/or
# ports, instead of the default. See also the <VirtualHost>
# directive.
#
# Change this to Listen on specific IP addresses as shown below to 
# prevent Apache from glomming onto all bound IP addresses.
#
#Listen 12.34.56.78:80
Listen 80

#
# Dynamic Shared Object (DSO) Support
#
# To be able to use the functionality of a module which was built as a DSO you
# have to place corresponding `LoadModule' lines at this location so the
# directives contained in it are actually available _before_ they are used.
# Statically compiled modules (those listed by `httpd -l') do not need
# to be loaded here.
#
# Example:
# LoadModule foo_module modules/mod_foo.so
#
Include conf.modules.d/*.conf
----

In each of these you can modify directives to impact the functionality of the server. For example, Listen is a directive that regulates the port that your server is listening to. 80 is the default but you may want to change this to 8080 for testing reasons. You would have to update your AWS security profiles to accommodate this port and add a :8080 to the end of your URL request to the server. 

Having seen this, it's important to note that Apache needs to be restarted every time a change is made to a configuration file as the files are read anew at every start/restart. To do this:

 $ sudo service httpd restart

Everything should go well so long as you didn't include some extra or unrecognizable characters in the httpd.conf file. Reload your web page on your browser. Honestly, you won't see any performance change as you are the only client on the server but just note that Apache has had some performance changes done via changes to the httpd.conf file.


=== Step 3: Modify Apache: Modules and Directives

Now cd into the `/etc/httpd/modules`. Once in there `ls` to show all of the files. You'll see that a number of files end with `.so'. If you view the contents of any of the .so files (e.g., `status.load`), you won't see much that you can work with. These are tools to increase the core funtionality of the server and they don't ever really get updated. 

Sticking with Status, open status.conf in your editor:

 $ sudo nano status.conf

You'll see a relatively small configuration file here. The point of the server-status module is to have Apache return server status information to the browser when requested. You can check this out by typing the following in your browser address bar:

 http://YOUR.PUBLIC.IP.ADDRESS/server-status

What you should see is a Forbidden error. What this tells us is that the module is running (server-status) but the directives are not set such that we can access the information. Returning to you status.conf, locate the block that starts with

 <Location /server-status>

In that block, modify the text to be:

.server-status.conf
[source,apache]
----
SetHandler server-status
order deny,allow
deny from all
allow from all
----

Save your changes and restart Apache. Then reload your page:

 http://YOUR.IP.ADDRESS/server-status

You should see the server-status information. Now, you have successfully identified a module and modified its directives to change its behavior. Now let's load a module that is not currently part of the core Apache functionality


=== Other issues

You have now gotten a good view of Apache. You should understand the folder and file structures, modules, and directives. If you'd like to stop the server, simply give the server a `sudo service httpd stop`. This exercise gives you an up-close an personal view of web servers and their role in managing a variety of network layers (ports, addressing, sessions, applications). As we've mentioned in class, many pieces of technology touch many network layers.

= Stop your instances at this point. 

