# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", inline: "echo Starting alice and bob virtual machines"
  
  config.vm.define "alice" do |alice|
    alice.vm.box = "ubuntu/trusty64"
    alice.vm.network "private_network", ip: "192.168.100.24"
    alice.vm.box_check_update = false
    alice.vm.hostname = "alice"
  end
  
  config.vm.define "bob" do |bob|
    bob.vm.box = "ubuntu/trusty64"
    bob.vm.network "private_network", ip: "192.168.100.25"
    bob.vm.box_check_update = false
    alice.vm.hostname = "bob"
  end

end
